server:
    port: 8099
spring:
    datasource:
        url: jdbc:mysql://192.168.50.50:3306/test?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: mysql123


mybatis-plus:
    mapper-locations: classpath*:mapper/*Mapper.xml


logging:
    level:
        com.test.demo.dao: debug